# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-18 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubspotCTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the CTA. This is just to identify the CTA when you want to place it into a page.', max_length=300)),
                ('embed_code', models.TextField()),
            ],
            options={
                'verbose_name': 'Hubspot CTA',
                'verbose_name_plural': 'Hubspot CTAs',
            },
        ),
        migrations.CreateModel(
            name='HubspotCTAPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_hubspot_hubspotctapluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_hubspot.HubspotCTA')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HubspotForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the form. This is just to identify the form when you want to place it into a page.', max_length=300)),
                ('embed_code', models.TextField()),
            ],
            options={
                'verbose_name': 'Hubspot form',
                'verbose_name_plural': 'Hubspot forms',
            },
        ),
        migrations.CreateModel(
            name='HubspotFormPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_hubspot_hubspotformpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_hubspot.HubspotForm')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
